# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Hemanth\Desktop\jarvisgui\Jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jarvis(object):
    def setupUi(self, Jarvis):
        Jarvis.setObjectName("Jarvis")
        Jarvis.resize(1490, 870)
        self.label = QtWidgets.QLabel(Jarvis)
        self.label.setGeometry(QtCore.QRect(0, 0, 1491, 871))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\Hemanth\\Desktop\\jarvisgui\\../Jarvis/jarvis 4.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Jarvis)
        self.pushButton.setGeometry(QtCore.QRect(1120, 780, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Jarvis)
        self.pushButton_2.setGeometry(QtCore.QRect(1260, 780, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Jarvis)
        self.label_2.setGeometry(QtCore.QRect(10, -40, 421, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\Hemanth\\Desktop\\jarvisgui\\../Jarvis/jarvis 3.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Jarvis)
        self.textBrowser.setGeometry(QtCore.QRect(730, 20, 361, 61))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Jarvis)
        self.textBrowser_2.setGeometry(QtCore.QRect(1100, 20, 361, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"borderradius:none;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(Jarvis)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 211, 341))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\Hemanth\\Desktop\\jarvisgui\\../Jarvis/Jarvis 2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Jarvis)
        self.label_4.setGeometry(QtCore.QRect(450, 20, 231, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\Hemanth\\Desktop\\jarvisgui\\../Jarvis/jarvis hightech.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Jarvis)
        self.label_6.setGeometry(QtCore.QRect(1010, 480, 451, 281))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\Hemanth\\Desktop\\jarvisgui\\../Jarvis/jarvis model.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Jarvis)
        QtCore.QMetaObject.connectSlotsByName(Jarvis)

    def retranslateUi(self, Jarvis):
        _translate = QtCore.QCoreApplication.translate
        Jarvis.setWindowTitle(_translate("Jarvis", "Dialog"))
        self.pushButton.setText(_translate("Jarvis", "RUN"))
        self.pushButton_2.setText(_translate("Jarvis", "TERMINATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvis = QtWidgets.QDialog()
    ui = Ui_Jarvis()
    ui.setupUi(Jarvis)
    Jarvis.show()
    sys.exit(app.exec_())
